name: movie_streaming_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  google_fonts: ^6.2.1
  reactive_button: ^0.0.9
  dartz: ^0.10.1
  dio: ^5.7.0
  logger: ^2.4.0
  get_it: ^8.0.2
  shared_preferences: ^2.3.2
  flutter_svg: ^2.0.13
  fan_carousel_image_slider: ^1.0.1
  video_player: ^2.9.2
  youtube_player_flutter: ^9.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
